<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Carbon\Carbon;
class DashboardController extends Controller
{
    public function dashboard()
    {
        $year = Carbon::now()->format('Y');
        $jumlah_pembelajaran = \App\Pembelajaran::all()->count();
        $pembelajaran_c1 = \App\Pembelajaran::whereMonth('created_at', 1)->whereYear('created_at', $year)->count();
        $pembelajaran_c2 = \App\Pembelajaran::whereMonth('created_at', 2)->whereYear('created_at', $year)->count();
        $pembelajaran_c3 = \App\Pembelajaran::whereMonth('created_at', 3)->whereYear('created_at', $year)->count();
        $pembelajaran_c4 = \App\Pembelajaran::whereMonth('created_at', 4)->whereYear('created_at', $year)->count();
        $pembelajaran_c5 = \App\Pembelajaran::whereMonth('created_at', 5)->whereYear('created_at', $year)->count();
        $pembelajaran_c6 = \App\Pembelajaran::whereMonth('created_at', 6)->whereYear('created_at', $year)->count();
        $pembelajaran_c7 = \App\Pembelajaran::whereMonth('created_at', 7)->whereYear('created_at', $year)->count();
        $pembelajaran_c8 = \App\Pembelajaran::whereMonth('created_at', 8)->whereYear('created_at', $year)->count();
        $pembelajaran_c9 = \App\Pembelajaran::whereMonth('created_at', 9)->whereYear('created_at', $year)->count();
        $pembelajaran_c10 = \App\Pembelajaran::whereMonth('created_at', 10)->whereYear('created_at', $year)->count();
        $pembelajaran_c11 = \App\Pembelajaran::whereMonth('created_at', 11)->whereYear('created_at', $year)->count();
        $pembelajaran_c12 = \App\Pembelajaran::whereMonth('created_at', 12)->whereYear('created_at', $year)->count();
        $pembelajaran_u1 = \App\Pembelajaran::whereMonth('updated_at', 1)->whereYear('updated_at', $year)->count();
        $pembelajaran_u2 = \App\Pembelajaran::whereMonth('updated_at', 2)->whereYear('updated_at', $year)->count();
        $pembelajaran_u3 = \App\Pembelajaran::whereMonth('updated_at', 3)->whereYear('updated_at', $year)->count();
        $pembelajaran_u4 = \App\Pembelajaran::whereMonth('updated_at', 4)->whereYear('updated_at', $year)->count();
        $pembelajaran_u5 = \App\Pembelajaran::whereMonth('updated_at', 5)->whereYear('updated_at', $year)->count();
        $pembelajaran_u6 = \App\Pembelajaran::whereMonth('updated_at', 6)->whereYear('updated_at', $year)->count();
        $pembelajaran_u7 = \App\Pembelajaran::whereMonth('updated_at', 7)->whereYear('updated_at', $year)->count();
        $pembelajaran_u8 = \App\Pembelajaran::whereMonth('updated_at', 8)->whereYear('updated_at', $year)->count();
        $pembelajaran_u9 = \App\Pembelajaran::whereMonth('updated_at', 9)->whereYear('updated_at', $year)->count();
        $pembelajaran_u10 = \App\Pembelajaran::whereMonth('updated_at', 10)->whereYear('updated_at', $year)->count();
        $pembelajaran_u11 = \App\Pembelajaran::whereMonth('updated_at', 11)->whereYear('updated_at', $year)->count();
        $pembelajaran_u12 = \App\Pembelajaran::whereMonth('updated_at', 12)->whereYear('updated_at', $year)->count();
        $pengumuman_c1 = \App\Pengumuman::whereMonth('created_at', 1)->whereYear('created_at', $year)->count();
        $pengumuman_c2 = \App\Pengumuman::whereMonth('created_at', 2)->whereYear('created_at', $year)->count();
        $pengumuman_c3 = \App\Pengumuman::whereMonth('created_at', 3)->whereYear('created_at', $year)->count();
        $pengumuman_c4 = \App\Pengumuman::whereMonth('created_at', 4)->whereYear('created_at', $year)->count();
        $pengumuman_c5 = \App\Pengumuman::whereMonth('created_at', 5)->whereYear('created_at', $year)->count();
        $pengumuman_c6 = \App\Pengumuman::whereMonth('created_at', 6)->whereYear('created_at', $year)->count();
        $pengumuman_c7 = \App\Pengumuman::whereMonth('created_at', 7)->whereYear('created_at', $year)->count();
        $pengumuman_c8 = \App\Pengumuman::whereMonth('created_at', 8)->whereYear('created_at', $year)->count();
        $pengumuman_c9 = \App\Pengumuman::whereMonth('created_at', 9)->whereYear('created_at', $year)->count();
        $pengumuman_c10 = \App\Pengumuman::whereMonth('created_at', 10)->whereYear('created_at', $year)->count();
        $pengumuman_c11 = \App\Pengumuman::whereMonth('created_at', 11)->whereYear('created_at', $year)->count();
        $pengumuman_c12 = \App\Pengumuman::whereMonth('created_at', 12)->whereYear('created_at', $year)->count();
        $pengumuman_u1 = \App\Pengumuman::whereMonth('updated_at', 1)->whereYear('updated_at', $year)->count();
        $pengumuman_u2 = \App\Pengumuman::whereMonth('updated_at', 2)->whereYear('updated_at', $year)->count();
        $pengumuman_u3 = \App\Pengumuman::whereMonth('updated_at', 3)->whereYear('updated_at', $year)->count();
        $pengumuman_u4 = \App\Pengumuman::whereMonth('updated_at', 4)->whereYear('updated_at', $year)->count();
        $pengumuman_u5 = \App\Pengumuman::whereMonth('updated_at', 5)->whereYear('updated_at', $year)->count();
        $pengumuman_u6 = \App\Pengumuman::whereMonth('updated_at', 6)->whereYear('updated_at', $year)->count();
        $pengumuman_u7 = \App\Pengumuman::whereMonth('updated_at', 7)->whereYear('updated_at', $year)->count();
        $pengumuman_u8 = \App\Pengumuman::whereMonth('updated_at', 8)->whereYear('updated_at', $year)->count();
        $pengumuman_u9 = \App\Pengumuman::whereMonth('updated_at', 9)->whereYear('updated_at', $year)->count();
        $pengumuman_u10 = \App\Pengumuman::whereMonth('updated_at', 10)->whereYear('updated_at', $year)->count();
        $pengumuman_u11 = \App\Pengumuman::whereMonth('updated_at', 11)->whereYear('updated_at', $year)->count();
        $pengumuman_u12 = \App\Pengumuman::whereMonth('updated_at', 12)->whereYear('updated_at', $year)->count();
        $kegiatan_c1 = \App\Kegiatan::whereMonth('created_at', 1)->whereYear('created_at', $year)->count();
        $kegiatan_c2 = \App\Kegiatan::whereMonth('created_at', 2)->whereYear('created_at', $year)->count();
        $kegiatan_c3 = \App\Kegiatan::whereMonth('created_at', 3)->whereYear('created_at', $year)->count();
        $kegiatan_c4 = \App\Kegiatan::whereMonth('created_at', 4)->whereYear('created_at', $year)->count();
        $kegiatan_c5 = \App\Kegiatan::whereMonth('created_at', 5)->whereYear('created_at', $year)->count();
        $kegiatan_c6 = \App\Kegiatan::whereMonth('created_at', 6)->whereYear('created_at', $year)->count();
        $kegiatan_c7 = \App\Kegiatan::whereMonth('created_at', 7)->whereYear('created_at', $year)->count();
        $kegiatan_c8 = \App\Kegiatan::whereMonth('created_at', 8)->whereYear('created_at', $year)->count();
        $kegiatan_c9 = \App\Kegiatan::whereMonth('created_at', 9)->whereYear('created_at', $year)->count();
        $kegiatan_c10 = \App\Kegiatan::whereMonth('created_at', 10)->whereYear('created_at', $year)->count();
        $kegiatan_c11 = \App\Kegiatan::whereMonth('created_at', 11)->whereYear('created_at', $year)->count();
        $kegiatan_c12 = \App\Kegiatan::whereMonth('created_at', 12)->whereYear('created_at', $year)->count();
        $kegiatan_u1 = \App\Kegiatan::whereMonth('updated_at', 1)->whereYear('updated_at', $year)->count();
        $kegiatan_u2 = \App\Kegiatan::whereMonth('updated_at', 2)->whereYear('updated_at', $year)->count();
        $kegiatan_u3 = \App\Kegiatan::whereMonth('updated_at', 3)->whereYear('updated_at', $year)->count();
        $kegiatan_u4 = \App\Kegiatan::whereMonth('updated_at', 4)->whereYear('updated_at', $year)->count();
        $kegiatan_u5 = \App\Kegiatan::whereMonth('updated_at', 5)->whereYear('updated_at', $year)->count();
        $kegiatan_u6 = \App\Kegiatan::whereMonth('updated_at', 6)->whereYear('updated_at', $year)->count();
        $kegiatan_u7 = \App\Kegiatan::whereMonth('updated_at', 7)->whereYear('updated_at', $year)->count();
        $kegiatan_u8 = \App\Kegiatan::whereMonth('updated_at', 8)->whereYear('updated_at', $year)->count();
        $kegiatan_u9 = \App\Kegiatan::whereMonth('updated_at', 9)->whereYear('updated_at', $year)->count();
        $kegiatan_u10 = \App\Kegiatan::whereMonth('updated_at', 10)->whereYear('updated_at', $year)->count();
        $kegiatan_u11 = \App\Kegiatan::whereMonth('updated_at', 11)->whereYear('updated_at', $year)->count();
        $kegiatan_u12 = \App\Kegiatan::whereMonth('updated_at', 12)->whereYear('updated_at', $year)->count();
        $galeri_c1 = \App\Galeri::whereMonth('created_at', 1)->whereYear('created_at', $year)->count();
        $galeri_c2 = \App\Galeri::whereMonth('created_at', 2)->whereYear('created_at', $year)->count();
        $galeri_c3 = \App\Galeri::whereMonth('created_at', 3)->whereYear('created_at', $year)->count();
        $galeri_c4 = \App\Galeri::whereMonth('created_at', 4)->whereYear('created_at', $year)->count();
        $galeri_c5 = \App\Galeri::whereMonth('created_at', 5)->whereYear('created_at', $year)->count();
        $galeri_c6 = \App\Galeri::whereMonth('created_at', 6)->whereYear('created_at', $year)->count();
        $galeri_c7 = \App\Galeri::whereMonth('created_at', 7)->whereYear('created_at', $year)->count();
        $galeri_c8 = \App\Galeri::whereMonth('created_at', 8)->whereYear('created_at', $year)->count();
        $galeri_c9 = \App\Galeri::whereMonth('created_at', 9)->whereYear('created_at', $year)->count();
        $galeri_c10 = \App\Galeri::whereMonth('created_at', 10)->whereYear('created_at', $year)->count();
        $galeri_c11 = \App\Galeri::whereMonth('created_at', 11)->whereYear('created_at', $year)->count();
        $galeri_c12 = \App\Galeri::whereMonth('created_at', 12)->whereYear('created_at', $year)->count();
        $galeri_u1 = \App\Galeri::whereMonth('updated_at', 1)->whereYear('updated_at', $year)->count();
        $galeri_u2 = \App\Galeri::whereMonth('updated_at', 2)->whereYear('updated_at', $year)->count();
        $galeri_u3 = \App\Galeri::whereMonth('updated_at', 3)->whereYear('updated_at', $year)->count();
        $galeri_u4 = \App\Galeri::whereMonth('updated_at', 4)->whereYear('updated_at', $year)->count();
        $galeri_u5 = \App\Galeri::whereMonth('updated_at', 5)->whereYear('updated_at', $year)->count();
        $galeri_u6 = \App\Galeri::whereMonth('updated_at', 6)->whereYear('updated_at', $year)->count();
        $galeri_u7 = \App\Galeri::whereMonth('updated_at', 7)->whereYear('updated_at', $year)->count();
        $galeri_u8 = \App\Galeri::whereMonth('updated_at', 8)->whereYear('updated_at', $year)->count();
        $galeri_u9 = \App\Galeri::whereMonth('updated_at', 9)->whereYear('updated_at', $year)->count();
        $galeri_u10 = \App\Galeri::whereMonth('updated_at', 10)->whereYear('updated_at', $year)->count();
        $galeri_u11 = \App\Galeri::whereMonth('updated_at', 11)->whereYear('updated_at', $year)->count();
        $galeri_u12 = \App\Galeri::whereMonth('updated_at', 12)->whereYear('updated_at', $year)->count();
        $saran_c1 = \App\Kontak::whereMonth('created_at', 1)->whereYear('created_at', $year)->count();
        $saran_c2 = \App\Kontak::whereMonth('created_at', 2)->whereYear('created_at', $year)->count();
        $saran_c3 = \App\Kontak::whereMonth('created_at', 3)->whereYear('created_at', $year)->count();
        $saran_c4 = \App\Kontak::whereMonth('created_at', 4)->whereYear('created_at', $year)->count();
        $saran_c5 = \App\Kontak::whereMonth('created_at', 5)->whereYear('created_at', $year)->count();
        $saran_c6 = \App\Kontak::whereMonth('created_at', 6)->whereYear('created_at', $year)->count();
        $saran_c7 = \App\Kontak::whereMonth('created_at', 7)->whereYear('created_at', $year)->count();
        $saran_c8 = \App\Kontak::whereMonth('created_at', 8)->whereYear('created_at', $year)->count();
        $saran_c9 = \App\Kontak::whereMonth('created_at', 9)->whereYear('created_at', $year)->count();
        $saran_c10 = \App\Kontak::whereMonth('created_at', 10)->whereYear('created_at', $year)->count();
        $saran_c11 = \App\Kontak::whereMonth('created_at', 11)->whereYear('created_at', $year)->count();
        $saran_c12 = \App\Kontak::whereMonth('created_at', 12)->whereYear('created_at', $year)->count();
        $saran_u1 = \App\Kontak::whereMonth('updated_at', 1)->whereYear('updated_at', $year)->count();
        $saran_u2 = \App\Kontak::whereMonth('updated_at', 2)->whereYear('updated_at', $year)->count();
        $saran_u3 = \App\Kontak::whereMonth('updated_at', 3)->whereYear('updated_at', $year)->count();
        $saran_u4 = \App\Kontak::whereMonth('updated_at', 4)->whereYear('updated_at', $year)->count();
        $saran_u5 = \App\Kontak::whereMonth('updated_at', 5)->whereYear('updated_at', $year)->count();
        $saran_u6 = \App\Kontak::whereMonth('updated_at', 6)->whereYear('updated_at', $year)->count();
        $saran_u7 = \App\Kontak::whereMonth('updated_at', 7)->whereYear('updated_at', $year)->count();
        $saran_u8 = \App\Kontak::whereMonth('updated_at', 8)->whereYear('updated_at', $year)->count();
        $saran_u9 = \App\Kontak::whereMonth('updated_at', 9)->whereYear('updated_at', $year)->count();
        $saran_u10 = \App\Kontak::whereMonth('updated_at', 10)->whereYear('updated_at', $year)->count();
        $saran_u11 = \App\Kontak::whereMonth('updated_at', 11)->whereYear('updated_at', $year)->count();
        $saran_u12 = \App\Kontak::whereMonth('updated_at', 12)->whereYear('updated_at', $year)->count();
        $studi_c1 = \App\Studi::whereMonth('created_at', 1)->whereYear('created_at', $year)->count();
        $studi_c2 = \App\Studi::whereMonth('created_at', 2)->whereYear('created_at', $year)->count();
        $studi_c3 = \App\Studi::whereMonth('created_at', 3)->whereYear('created_at', $year)->count();
        $studi_c4 = \App\Studi::whereMonth('created_at', 4)->whereYear('created_at', $year)->count();
        $studi_c5 = \App\Studi::whereMonth('created_at', 5)->whereYear('created_at', $year)->count();
        $studi_c6 = \App\Studi::whereMonth('created_at', 6)->whereYear('created_at', $year)->count();
        $studi_c7 = \App\Studi::whereMonth('created_at', 7)->whereYear('created_at', $year)->count();
        $studi_c8 = \App\Studi::whereMonth('created_at', 8)->whereYear('created_at', $year)->count();
        $studi_c9 = \App\Studi::whereMonth('created_at', 9)->whereYear('created_at', $year)->count();
        $studi_c10 = \App\Studi::whereMonth('created_at', 10)->whereYear('created_at', $year)->count();
        $studi_c11 = \App\Studi::whereMonth('created_at', 11)->whereYear('created_at', $year)->count();
        $studi_c12 = \App\Studi::whereMonth('created_at', 12)->whereYear('created_at', $year)->count();
        $studi_u1 = \App\Studi::whereMonth('updated_at', 1)->whereYear('updated_at', $year)->count();
        $studi_u2 = \App\Studi::whereMonth('updated_at', 2)->whereYear('updated_at', $year)->count();
        $studi_u3 = \App\Studi::whereMonth('updated_at', 3)->whereYear('updated_at', $year)->count();
        $studi_u4 = \App\Studi::whereMonth('updated_at', 4)->whereYear('updated_at', $year)->count();
        $studi_u5 = \App\Studi::whereMonth('updated_at', 5)->whereYear('updated_at', $year)->count();
        $studi_u6 = \App\Studi::whereMonth('updated_at', 6)->whereYear('updated_at', $year)->count();
        $studi_u7 = \App\Studi::whereMonth('updated_at', 7)->whereYear('updated_at', $year)->count();
        $studi_u8 = \App\Studi::whereMonth('updated_at', 8)->whereYear('updated_at', $year)->count();
        $studi_u9 = \App\Studi::whereMonth('updated_at', 9)->whereYear('updated_at', $year)->count();
        $studi_u10 = \App\Studi::whereMonth('updated_at', 10)->whereYear('updated_at', $year)->count();
        $studi_u11 = \App\Studi::whereMonth('updated_at', 11)->whereYear('updated_at', $year)->count();
        $studi_u12 = \App\Studi::whereMonth('updated_at', 12)->whereYear('updated_at', $year)->count();
        $guru_c1 = \App\Guru::whereMonth('created_at', 1)->whereYear('created_at', $year)->count();
        $guru_c2 = \App\Guru::whereMonth('created_at', 2)->whereYear('created_at', $year)->count();
        $guru_c3 = \App\Guru::whereMonth('created_at', 3)->whereYear('created_at', $year)->count();
        $guru_c4 = \App\Guru::whereMonth('created_at', 4)->whereYear('created_at', $year)->count();
        $guru_c5 = \App\Guru::whereMonth('created_at', 5)->whereYear('created_at', $year)->count();
        $guru_c6 = \App\Guru::whereMonth('created_at', 6)->whereYear('created_at', $year)->count();
        $guru_c7 = \App\Guru::whereMonth('created_at', 7)->whereYear('created_at', $year)->count();
        $guru_c8 = \App\Guru::whereMonth('created_at', 8)->whereYear('created_at', $year)->count();
        $guru_c9 = \App\Guru::whereMonth('created_at', 9)->whereYear('created_at', $year)->count();
        $guru_c10 = \App\Guru::whereMonth('created_at', 10)->whereYear('created_at', $year)->count();
        $guru_c11 = \App\Guru::whereMonth('created_at', 11)->whereYear('created_at', $year)->count();
        $guru_c12 = \App\Guru::whereMonth('created_at', 12)->whereYear('created_at', $year)->count();
        $guru_u1 = \App\Guru::whereMonth('updated_at', 1)->whereYear('updated_at', $year)->count();
        $guru_u2 = \App\Guru::whereMonth('updated_at', 2)->whereYear('updated_at', $year)->count();
        $guru_u3 = \App\Guru::whereMonth('updated_at', 3)->whereYear('updated_at', $year)->count();
        $guru_u4 = \App\Guru::whereMonth('updated_at', 4)->whereYear('updated_at', $year)->count();
        $guru_u5 = \App\Guru::whereMonth('updated_at', 5)->whereYear('updated_at', $year)->count();
        $guru_u6 = \App\Guru::whereMonth('updated_at', 6)->whereYear('updated_at', $year)->count();
        $guru_u7 = \App\Guru::whereMonth('updated_at', 7)->whereYear('updated_at', $year)->count();
        $guru_u8 = \App\Guru::whereMonth('updated_at', 8)->whereYear('updated_at', $year)->count();
        $guru_u9 = \App\Guru::whereMonth('updated_at', 9)->whereYear('updated_at', $year)->count();
        $guru_u10 = \App\Guru::whereMonth('updated_at', 10)->whereYear('updated_at', $year)->count();
        $guru_u11 = \App\Guru::whereMonth('updated_at', 11)->whereYear('updated_at', $year)->count();
        $guru_u12 = \App\Guru::whereMonth('updated_at', 12)->whereYear('updated_at', $year)->count();
        $jurusan_c1 = \App\Jurusan::whereMonth('created_at', 1)->whereYear('created_at', $year)->count();
        $jurusan_c2 = \App\Jurusan::whereMonth('created_at', 2)->whereYear('created_at', $year)->count();
        $jurusan_c3 = \App\Jurusan::whereMonth('created_at', 3)->whereYear('created_at', $year)->count();
        $jurusan_c4 = \App\Jurusan::whereMonth('created_at', 4)->whereYear('created_at', $year)->count();
        $jurusan_c5 = \App\Jurusan::whereMonth('created_at', 5)->whereYear('created_at', $year)->count();
        $jurusan_c6 = \App\Jurusan::whereMonth('created_at', 6)->whereYear('created_at', $year)->count();
        $jurusan_c7 = \App\Jurusan::whereMonth('created_at', 7)->whereYear('created_at', $year)->count();
        $jurusan_c8 = \App\Jurusan::whereMonth('created_at', 8)->whereYear('created_at', $year)->count();
        $jurusan_c9 = \App\Jurusan::whereMonth('created_at', 9)->whereYear('created_at', $year)->count();
        $jurusan_c10 = \App\Jurusan::whereMonth('created_at', 10)->whereYear('created_at', $year)->count();
        $jurusan_c11 = \App\Jurusan::whereMonth('created_at', 11)->whereYear('created_at', $year)->count();
        $jurusan_c12 = \App\Jurusan::whereMonth('created_at', 12)->whereYear('created_at', $year)->count();
        $jurusan_u1 = \App\Jurusan::whereMonth('updated_at', 1)->whereYear('updated_at', $year)->count();
        $jurusan_u2 = \App\Jurusan::whereMonth('updated_at', 2)->whereYear('updated_at', $year)->count();
        $jurusan_u3 = \App\Jurusan::whereMonth('updated_at', 3)->whereYear('updated_at', $year)->count();
        $jurusan_u4 = \App\Jurusan::whereMonth('updated_at', 4)->whereYear('updated_at', $year)->count();
        $jurusan_u5 = \App\Jurusan::whereMonth('updated_at', 5)->whereYear('updated_at', $year)->count();
        $jurusan_u6 = \App\Jurusan::whereMonth('updated_at', 6)->whereYear('updated_at', $year)->count();
        $jurusan_u7 = \App\Jurusan::whereMonth('updated_at', 7)->whereYear('updated_at', $year)->count();
        $jurusan_u8 = \App\Jurusan::whereMonth('updated_at', 8)->whereYear('updated_at', $year)->count();
        $jurusan_u9 = \App\Jurusan::whereMonth('updated_at', 9)->whereYear('updated_at', $year)->count();
        $jurusan_u10 = \App\Jurusan::whereMonth('updated_at', 10)->whereYear('updated_at', $year)->count();
        $jurusan_u11 = \App\Jurusan::whereMonth('updated_at', 11)->whereYear('updated_at', $year)->count();
        $jurusan_u12 = \App\Jurusan::whereMonth('updated_at', 12)->whereYear('updated_at', $year)->count();
        $jumlah_pengumuman = \App\Pengumuman::all()->count();
        $jumlah_kegiatan = \App\Kegiatan::all()->count();
        $jumlah_galeri = \App\Galeri::all()->count();
        $jumlah_saran = \App\Kontak::all()->count();
        $jumlah_studi = \App\Studi::all()->count();
        $jumlah_guru = \App\Guru::all()->count();
        $jumlah_jurusan = \App\Jurusan::all()->count();
        return view('backend.dashboard', [
            'jumlah_pembelajaran' => $jumlah_pembelajaran,
            'pembelajaran_c1' => $pembelajaran_c1,
            'pembelajaran_c2' => $pembelajaran_c2,
            'pembelajaran_c3' => $pembelajaran_c3,
            'pembelajaran_c4' => $pembelajaran_c4,
            'pembelajaran_c5' => $pembelajaran_c5,
            'pembelajaran_c6' => $pembelajaran_c6,
            'pembelajaran_c7' => $pembelajaran_c7,
            'pembelajaran_c8' => $pembelajaran_c8,
            'pembelajaran_c9' => $pembelajaran_c9,
            'pembelajaran_c10' => $pembelajaran_c10,
            'pembelajaran_c11' => $pembelajaran_c11,
            'pembelajaran_c12' => $pembelajaran_c12,
            'pembelajaran_u1' => $pembelajaran_u1,
            'pembelajaran_u2' => $pembelajaran_u2,
            'pembelajaran_u3' => $pembelajaran_u3,
            'pembelajaran_u4' => $pembelajaran_u4,
            'pembelajaran_u5' => $pembelajaran_u5,
            'pembelajaran_u6' => $pembelajaran_u6,
            'pembelajaran_u7' => $pembelajaran_u7,
            'pembelajaran_u8' => $pembelajaran_u8,
            'pembelajaran_u9' => $pembelajaran_u9,
            'pembelajaran_u10' => $pembelajaran_u10,
            'pembelajaran_u11' => $pembelajaran_u11,
            'pembelajaran_u12' => $pembelajaran_u12,
            'pengumuman_c1' => $pengumuman_c1,
            'pengumuman_c2' => $pengumuman_c2,
            'pengumuman_c3' => $pengumuman_c3,
            'pengumuman_c4' => $pengumuman_c4,
            'pengumuman_c5' => $pengumuman_c5,
            'pengumuman_c6' => $pengumuman_c6,
            'pengumuman_c7' => $pengumuman_c7,
            'pengumuman_c8' => $pengumuman_c8,
            'pengumuman_c9' => $pengumuman_c9,
            'pengumuman_c10' => $pengumuman_c10,
            'pengumuman_c11' => $pengumuman_c11,
            'pengumuman_c12' => $pengumuman_c12,
            'pengumuman_u1' => $pengumuman_u1,
            'pengumuman_u2' => $pengumuman_u2,
            'pengumuman_u3' => $pengumuman_u3,
            'pengumuman_u4' => $pengumuman_u4,
            'pengumuman_u5' => $pengumuman_u5,
            'pengumuman_u6' => $pengumuman_u6,
            'pengumuman_u7' => $pengumuman_u7,
            'pengumuman_u8' => $pengumuman_u8,
            'pengumuman_u9' => $pengumuman_u9,
            'pengumuman_u10' => $pengumuman_u10,
            'pengumuman_u11' => $pengumuman_u11,
            'pengumuman_u12' => $pengumuman_u12,
            'kegiatan_c1' => $kegiatan_c1,
            'kegiatan_c2' => $kegiatan_c2,
            'kegiatan_c3' => $kegiatan_c3,
            'kegiatan_c4' => $kegiatan_c4,
            'kegiatan_c5' => $kegiatan_c5,
            'kegiatan_c6' => $kegiatan_c6,
            'kegiatan_c7' => $kegiatan_c7,
            'kegiatan_c8' => $kegiatan_c8,
            'kegiatan_c9' => $kegiatan_c9,
            'kegiatan_c10' => $kegiatan_c10,
            'kegiatan_c11' => $kegiatan_c11,
            'kegiatan_c12' => $kegiatan_c12,
            'kegiatan_u1' => $kegiatan_u1,
            'kegiatan_u2' => $kegiatan_u2,
            'kegiatan_u3' => $kegiatan_u3,
            'kegiatan_u4' => $kegiatan_u4,
            'kegiatan_u5' => $kegiatan_u5,
            'kegiatan_u6' => $kegiatan_u6,
            'kegiatan_u7' => $kegiatan_u7,
            'kegiatan_u8' => $kegiatan_u8,
            'kegiatan_u9' => $kegiatan_u9,
            'kegiatan_u10' => $kegiatan_u10,
            'kegiatan_u11' => $kegiatan_u11,
            'kegiatan_u12' => $kegiatan_u12,
            'galeri_c1' => $galeri_c1,
            'galeri_c2' => $galeri_c2,
            'galeri_c3' => $galeri_c3,
            'galeri_c4' => $galeri_c4,
            'galeri_c5' => $galeri_c5,
            'galeri_c6' => $galeri_c6,
            'galeri_c7' => $galeri_c7,
            'galeri_c8' => $galeri_c8,
            'galeri_c9' => $galeri_c9,
            'galeri_c10' => $galeri_c10,
            'galeri_c11' => $galeri_c11,
            'galeri_c12' => $galeri_c12,
            'galeri_u1' => $galeri_u1,
            'galeri_u2' => $galeri_u2,
            'galeri_u3' => $galeri_u3,
            'galeri_u4' => $galeri_u4,
            'galeri_u5' => $galeri_u5,
            'galeri_u6' => $galeri_u6,
            'galeri_u7' => $galeri_u7,
            'galeri_u8' => $galeri_u8,
            'galeri_u9' => $galeri_u9,
            'galeri_u10' => $galeri_u10,
            'galeri_u11' => $galeri_u11,
            'galeri_u12' => $galeri_u12,
            'saran_c1' => $saran_c1,
            'saran_c2' => $saran_c2,
            'saran_c3' => $saran_c3,
            'saran_c4' => $saran_c4,
            'saran_c5' => $saran_c5,
            'saran_c6' => $saran_c6,
            'saran_c7' => $saran_c7,
            'saran_c8' => $saran_c8,
            'saran_c9' => $saran_c9,
            'saran_c10' => $saran_c10,
            'saran_c11' => $saran_c11,
            'saran_c12' => $saran_c12,
            'saran_u1' => $saran_u1,
            'saran_u2' => $saran_u2,
            'saran_u3' => $saran_u3,
            'saran_u4' => $saran_u4,
            'saran_u5' => $saran_u5,
            'saran_u6' => $saran_u6,
            'saran_u7' => $saran_u7,
            'saran_u8' => $saran_u8,
            'saran_u9' => $saran_u9,
            'saran_u10' => $saran_u10,
            'saran_u11' => $saran_u11,
            'saran_u12' => $saran_u12,
            'studi_c1' => $studi_c1,
            'studi_c2' => $studi_c2,
            'studi_c3' => $studi_c3,
            'studi_c4' => $studi_c4,
            'studi_c5' => $studi_c5,
            'studi_c6' => $studi_c6,
            'studi_c7' => $studi_c7,
            'studi_c8' => $studi_c8,
            'studi_c9' => $studi_c9,
            'studi_c10' => $studi_c10,
            'studi_c11' => $studi_c11,
            'studi_c12' => $studi_c12,
            'studi_u1' => $studi_u1,
            'studi_u2' => $studi_u2,
            'studi_u3' => $studi_u3,
            'studi_u4' => $studi_u4,
            'studi_u5' => $studi_u5,
            'studi_u6' => $studi_u6,
            'studi_u7' => $studi_u7,
            'studi_u8' => $studi_u8,
            'studi_u9' => $studi_u9,
            'studi_u10' => $studi_u10,
            'studi_u11' => $studi_u11,
            'studi_u12' => $studi_u12,
            'guru_c1' => $guru_c1,
            'guru_c2' => $guru_c2,
            'guru_c3' => $guru_c3,
            'guru_c4' => $guru_c4,
            'guru_c5' => $guru_c5,
            'guru_c6' => $guru_c6,
            'guru_c7' => $guru_c7,
            'guru_c8' => $guru_c8,
            'guru_c9' => $guru_c9,
            'guru_c10' => $guru_c10,
            'guru_c11' => $guru_c11,
            'guru_c12' => $guru_c12,
            'guru_u1' => $guru_u1,
            'guru_u2' => $guru_u2,
            'guru_u3' => $guru_u3,
            'guru_u4' => $guru_u4,
            'guru_u5' => $guru_u5,
            'guru_u6' => $guru_u6,
            'guru_u7' => $guru_u7,
            'guru_u8' => $guru_u8,
            'guru_u9' => $guru_u9,
            'guru_u10' => $guru_u10,
            'guru_u11' => $guru_u11,
            'guru_u12' => $guru_u12,
            'jurusan_c1' => $jurusan_c1,
            'jurusan_c2' => $jurusan_c2,
            'jurusan_c3' => $jurusan_c3,
            'jurusan_c4' => $jurusan_c4,
            'jurusan_c5' => $jurusan_c5,
            'jurusan_c6' => $jurusan_c6,
            'jurusan_c7' => $jurusan_c7,
            'jurusan_c8' => $jurusan_c8,
            'jurusan_c9' => $jurusan_c9,
            'jurusan_c10' => $jurusan_c10,
            'jurusan_c11' => $jurusan_c11,
            'jurusan_c12' => $jurusan_c12,
            'jurusan_u1' => $jurusan_u1,
            'jurusan_u2' => $jurusan_u2,
            'jurusan_u3' => $jurusan_u3,
            'jurusan_u4' => $jurusan_u4,
            'jurusan_u5' => $jurusan_u5,
            'jurusan_u6' => $jurusan_u6,
            'jurusan_u7' => $jurusan_u7,
            'jurusan_u8' => $jurusan_u8,
            'jurusan_u9' => $jurusan_u9,
            'jurusan_u10' => $jurusan_u10,
            'jurusan_u11' => $jurusan_u11,
            'jurusan_u12' => $jurusan_u12,
            'jumlah_pengumuman' => $jumlah_pengumuman,
            'jumlah_jurusan' => $jumlah_jurusan,
            'jumlah_guru' => $jumlah_guru,
            'jumlah_studi' => $jumlah_studi,
            'jumlah_saran' => $jumlah_saran,
            'jumlah_galeri' => $jumlah_galeri,
            'jumlah_kegiatan' => $jumlah_kegiatan,
        ]);
    }
}
